# While the GitHub mirror is read-only, we keep this CI config
# for convenience to forks and pull requests.
#
# To submit a patch you can:
#
# * Create a Wikimedia Developer account and submit it to Wikimedia Gerrit
#   <https://www.mediawiki.org/wiki/Developer_account>,
#
# * Or, submit the output of `git diff origin/HEAD`
#   via <https://gerrit-patch-uploader.toolforge.org/>.
#
# * Or, create a pull request via GitHub and wait for someone
#   else to do one of the above.
#
name: Test

on:
  - push
  - pull_request

jobs:

  # Lint-only for basic assurance until next major version
  php72:
    name: PHP 7.2
    # Includes php7.1 - 8.0 and composer 2
    # https://github.com/actions/runner-images/blob/ubuntu18/20210318.0/images/linux/Ubuntu1804-README.md#php
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use PHP 7.2
        run: sudo update-alternatives --set php /usr/bin/php7.2
      - run: rm composer.json
      - run: composer require --dev php-parallel-lint/php-parallel-lint=1.3.2
      - run: composer exec -- parallel-lint . --exclude external --exclude vendor

  php:
    name: PHP ${{ matrix.php }}

    strategy:
      fail-fast: false
      matrix:
        include:
          # Includes php7.4 - 8.2 and composer 2
          # https://github.com/actions/runner-images/blob/ubuntu20/20221212.2/images/linux/Ubuntu2004-Readme.md#php
          - php: '7.4'
            os: ubuntu-20.04
          - php: '8.0'
            os: ubuntu-20.04
          - php: '8.1'
            os: ubuntu-20.04
          - php: '8.2'
            os: ubuntu-20.04

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use PHP ${{ matrix.php }}
      run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Test
      run: composer test
